POST http://localhost:8080/user/
Content-Type: application/json

{
    "username": "John",
    "password": "John",
    "email": "redcraft1234567890@gmail.com"
}

###

POST http://localhost:8080/user/login/
Content-Type: application/json

{
    "password": "James",
    "email": "james@czak.me"
}

###

POST http://localhost:8080/user/admin/
Content-Type: application/json

{
    "password": "John",
    "email": "redcraft1234567890@gmail.com",
    "newEmail": "redcraft1234567890@gmail.com"
}

###

POST http://localhost:8080/user/alg/add/
Content-Type: application/json

{
    "password": "James",
    "email": "james@czak.me",
    "id": "66a69f6cea11e37af2d8cb2d"
}

###

POST http://localhost:8080/user/alg/delete/
Content-Type: application/json

{
    "password": "James",
    "email": "james@czak.me",
    "id": "66a69f6cea11e37af2d8cb2d"
}

###

POST http://localhost:8080/algs/create/
Content-Type: application/json

{
    "cube": "3x3",
    "method": "cfop",
    "set": "pll",
    "alg": "ja",
    "data": "( R' U L' U2 ) ( R U' R' U2 ) R L",
    "img": "http://localhost:3000/idk",
    "name": "James",
    "password": "James",
    "email": "james@czak.me"
}

###

POST http://localhost:8080/algs/
Content-Type: application/json

###

POST http://localhost:8080/algs/
Content-Type: application/json

{
    "cube": "3x3",
    "method": "cfop",
    "set": "pll",
    "alg": "Ja"
}

###

POST http://localhost:8080/algs/id
Content-Type: application/json

{
    "id": "668439abf02fb64b90ede08a"
}

###

PATCH http://localhost:8080/algs/update/
Content-Type: application/json

{
    "old_data": {
        "cube": "3x3",
        "method": "cfop",
        "set": "pll",
        "alg": "ja"
    },
    "new_data": {
        "cube": "3x3",
        "method": "cfop",
        "set": "pll",
        "alg": "ja",
        "data": "( R U R' F' ) ( R U R' U' ) R' F R2 U' R'"
    },
    "name": "James",
    "password": "James",
    "email": "james@czak.me"
}

###

POST http://localhost:8080/algs/delete/
Content-Type: application/json

{
    "cube": {
        "cube": "3x3",
        "method": "cfop",
        "set": "pll",
        "alg": "ja"
    },
    "name": "James",
    "password": "James",
    "email": "james@czak.me"
}