POST http://localhost:8080/api/user/
Content-Type: application/json

{
    "username": "James",
    "password": "James",
    "email": "email@email.com"
}

###

GET http://localhost:8080/api/user/
Content-Type: application/json

{
    "name": "James",
    "password": "James",
    "email": "email@email.com"
}

###

POST http://localhost:8080/api/algs/
Content-Type: application/json

{
    "cube": "3x3",
    "method": "cfop",
    "set": "pll",
    "alg": "ja",
    "data": "( R' U L' U2 ) ( R U' R' U2 ) R L",
    "name": "James",
    "password": "James",
    "email": "email@email.com"
}

###

GET http://localhost:8080/api/algs/
Content-Type: application/json

{
    "cube": "3x3",
    "method": "cfop",
    "set": "pll",
    "alg": "ja"
}

###

GET http://localhost:8080/api/algs/id
Content-Type: application/json

{
    "id": "668439abf02fb64b90ede08a"
}

###

PATCH http://localhost:8080/api/algs/
Content-Type: application/json

{
    "old_data": {
        "cube": "3x3",
        "method": "cfop",
        "set": "pll",
        "alg": "ja"
    },
    "new_data": {
        "cube": "3x3",
        "method": "cfop",
        "set": "pll",
        "alg": "ja",
        "data": "( R U R' F' ) ( R U R' U' ) R' F R2 U' R'"
    },
    "name": "James",
    "password": "James",
    "email": "email@email.com"
}